version: '3'
services:
  url-shortener:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
